### ISSUE TITLE
Update Checklist for 1.17

### ISSUE THREAD

**Issue by andrewrynhard** [kubernetes-sigs/bootkube#1054]
- [x] Move to go modules (#1045)
- [x] Upgrade go to 1.13 (#1045)
- [x] Replace imports paths with new repo paths (#1045)
- [x] CRI lib update for checkpointer (#1048)
  - [ ] Import CRI library instead of copying
- [ ] Update render templates for 1.17
  - [x] Remove deprecated flags
  - [x] Add flags required by conformance (#1064)
- [ ] Update hack/* for 1.17
- [x] Upgrade CoreDNS (#1071)
  - [x] Deploy 2 replicas instead of a single one
  - [x] Setup Anti-affinity rules
- [ ] Set default pod priorities
- [ ] Anti-affinity rules for control plane components
- [ ] Add ability to specify kubeconfig context name
- [ ] Initial implementation for render patches (experimental)
- [ ] Conformance tests
- [ ] CI and testing
  - [ ] Where?
  - [ ] What?
- [ ] Revisit checkpointing and plan for improvements
- [ ] Revisit recovery and plan for improvements

**Comment by swade1987** [comment]
CoreDNS should probably be 'preferred' anti-affinity.

**Comment by swade1987** [comment]
I think some default pod priorities for the control plane would be useful.

**Comment by andrewrynhard** [comment]
> CoreDNS should probably be 'preferred' anti-affinity.

Curious about the reasoning here. To avoid failures in single control plane setups?

**Comment by swade1987** [comment]
@andrewrynhard exactly that reason.

**Comment by smekkley** [comment]
I wonder enabling healthcheck for apiserver and enabling PodSecurityPolicy by default for render are good candidate for 1.17, as kubeadm selfhosting option already support these. Sorry if these are already included in the list.

**Comment by andrewrynhard** [comment]
I'm a big 👍 for enabling `PodSecurityPolicy` and health checking.
